apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: postgres
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:hefanxu/argoRepo.git
    targetRevision: HEAD
    path: apps/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      selfHeal: true
      prune: true